name: app_chat
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.1+2
  equatable: ^2.0.5
  sqflite: ^2.3.3+1
  crypto: ^3.0.3
  encrypt: ^5.0.3
  path: ^1.9.0
  emoji_picker_flutter: ^2.1.1
  file_picker: ^8.0.6
  permission_handler: ^11.3.1
  photo_manager: ^3.2.2
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  get_it: ^7.7.0
  injectable: ^2.4.4
  another_flushbar: ^1.12.30
  go_router: ^14.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator:
  build_runner:


flutter:

  uses-material-design: true
  assets:
    - assets/images/
flutter_intl:
  enable: true

